### ISSUE TITLE
vec256 type declaration

### ISSUE THREAD

**Issue by ajgappmark** [supranational/sppark#15]
Hi, 
I am trying to build `ntt` part of sppark as independent C/C++ project for a project. However, the type declaration/definition for [vec256](https://github.com/supranational/sppark/blob/9a6bed51bd61d1adcb2eb0da79fed588651bc615/ntt/parameters/bls12_377.h#L17C13-L17C13)  is no where to be found under `sppark/` project. I even search into the codebase of `[blst](https://github.com/supranational/blst/tree/master)` and still I couldn't find it either.

Building sppark from cargo is no problem at all. However, as I mentioned that I am trying to build the ntt portion independently as C/C++/Cuda project and the type declaration for vec256 is no where to be found which would enable me to be able to successfully build.

I would greatly appreciate your response

**Comment by sandsentinel** [comment]
Hello,

The parameter files in `ntt/parameters/` should be included only on the host side, which we accomplish with an `#ifndef __CUDA_ARCH__` guard, [like this](https://github.com/supranational/sppark/blob/9a6bed51bd61d1adcb2eb0da79fed588651bc615/ntt/parameters.cuh#L35). We do this because `vec256` is not defined on the device side, so the CUDA compiler complains if it's made visible to the device side. This might be the cause of your issue.

I can also provide a basic C++ test program if you'd like.

**Comment by ajgappmark** [comment]
Hi,
If you can provide a basic C test program as well as perhaps a short script to independently build the ntt portion of project, I would great appreciate it.
Thanks

**Comment by ajgappmark** [comment]
Hi,
Thanks for your informative response. However one question
`
INCLUDES="-Isppark/ -Iblst/src/"
LIBS="-Lblst/ -lblst"
`
Is `-Lblst/` a typo, don't you mean something along lines of `-llibntt`?? 
Please check

**Comment by ajgappmark** [comment]
Thank you very much for your informative response. I will try this in a shortwhile.

**Comment by dot-asm** [comment]
> What's the distinction between these two and when one should use the fp_t over fr_t?

This is kind of a text-book question, it's a reflection of common terminology, or established lingo if you wish. Unfortunately we don't do text-book questions here, because this is not an educational project:-(

> What's the purpose [of this and that]

You leave no other choice but to conclude that you ask these questions for self-educational purposes. This regretfully falls beyond the scope of the project. In other words, we simply don't have time to spare to go into these kinds of details upon arbitrary requests. I'm sorry:-(

**Comment by ajgappmark** [comment]
Well I've figured out the answers to my earlier question. Thanks for your support and you guys have been more than helpful.
